<?php

namespace AxiomePayments\Service;

class CountryService {

    public static function getCountries(): array
    {
        return [
            'AF' => 'Afghanistan',
            'AL' => 'Albania',
            'DZ' => 'Algeria',
            'AS' => 'American Samoa',
            'AD' => 'Andorra',
            'AO' => 'Angola',
            'AI' => 'Anguilla',
            'AQ' => 'Antarctica',
            'AG' => 'Antigua and Barbuda',
            'AR' => 'Argentina',
            'AM' => 'Armenia',
            'AW' => 'Aruba',
            'AU' => 'Australia',
            'AT' => 'Austria',
            'AZ' => 'Azerbaijan',
            'BS' => 'Bahamas',
            'BH' => 'Bahrain',
            'BD' => 'Bangladesh',
            'BB' => 'Barbados',
            'BY' => 'Belarus',
            'BE' => 'Belgium',
            'BZ' => 'Belize',
            'BJ' => 'Benin',
            'BM' => 'Bermuda',
            'BT' => 'Bhutan',
            'BO' => 'Bolivia',
            'BA' => 'Bosnia and Herzegovina',
            'BW' => 'Botswana',
            'BV' => 'Bouvet Island',
            'BR' => 'Brazil',
            'BQ' => 'British Antarctic Territory',
            'IO' => 'British Indian Ocean Territory',
            'VG' => 'British Virgin Islands',
            'BN' => 'Brunei',
            'BG' => 'Bulgaria',
            'BF' => 'Burkina Faso',
            'BI' => 'Burundi',
            'KH' => 'Cambodia',
            'CM' => 'Cameroon',
            'CA' => 'Canada',
            'CT' => 'Canton and Enderbury Islands',
            'CV' => 'Cape Verde',
            'KY' => 'Cayman Islands',
            'CF' => 'Central African Republic',
            'TD' => 'Chad',
            'CL' => 'Chile',
            'CN' => 'China',
            'CX' => 'Christmas Island',
            'CC' => 'Cocos [Keeling] Islands',
            'CO' => 'Colombia',
            'KM' => 'Comoros',
            'CG' => 'Congo - Brazzaville',
            'CD' => 'Congo - Kinshasa',
            'CK' => 'Cook Islands',
            'CR' => 'Costa Rica',
            'HR' => 'Croatia',
            'CU' => 'Cuba',
            'CY' => 'Cyprus',
            'CZ' => 'Czech Republic',
            'CI' => 'Côte d’Ivoire',
            'DK' => 'Denmark',
            'DJ' => 'Djibouti',
            'DM' => 'Dominica',
            'DO' => 'Dominican Republic',
            'NQ' => 'Dronning Maud Land',
            'DD' => 'East Germany',
            'EC' => 'Ecuador',
            'EG' => 'Egypt',
            'SV' => 'El Salvador',
            'GQ' => 'Equatorial Guinea',
            'ER' => 'Eritrea',
            'EE' => 'Estonia',
            'ET' => 'Ethiopia',
            'FK' => 'Falkland Islands',
            'FO' => 'Faroe Islands',
            'FJ' => 'Fiji',
            'FI' => 'Finland',
            'FR' => 'France',
            'GF' => 'French Guiana',
            'PF' => 'French Polynesia',
            'TF' => 'French Southern Territories',
            'FQ' => 'French Southern and Antarctic Territories',
            'GA' => 'Gabon',
            'GM' => 'Gambia',
            'GE' => 'Georgia',
            'DE' => 'Germany',
            'GH' => 'Ghana',
            'GI' => 'Gibraltar',
            'GR' => 'Greece',
            'GL' => 'Greenland',
            'GD' => 'Grenada',
            'GP' => 'Guadeloupe',
            'GU' => 'Guam',
            'GT' => 'Guatemala',
            'GG' => 'Guernsey',
            'GN' => 'Guinea',
            'GW' => 'Guinea-Bissau',
            'GY' => 'Guyana',
            'HT' => 'Haiti',
            'HM' => 'Heard Island and McDonald Islands',
            'HN' => 'Honduras',
            'HK' => 'Hong Kong SAR China',
            'HU' => 'Hungary',
            'IS' => 'Iceland',
            'IN' => 'India',
            'ID' => 'Indonesia',
            'IR' => 'Iran',
            'IQ' => 'Iraq',
            'IE' => 'Ireland',
            'IM' => 'Isle of Man',
            'IL' => 'Israel',
            'IT' => 'Italy',
            'JM' => 'Jamaica',
            'JP' => 'Japan',
            'JE' => 'Jersey',
            'JT' => 'Johnston Island',
            'JO' => 'Jordan',
            'KZ' => 'Kazakhstan',
            'KE' => 'Kenya',
            'KI' => 'Kiribati',
            'KW' => 'Kuwait',
            'KG' => 'Kyrgyzstan',
            'LA' => 'Laos',
            'LV' => 'Latvia',
            'LB' => 'Lebanon',
            'LS' => 'Lesotho',
            'LR' => 'Liberia',
            'LY' => 'Libya',
            'LI' => 'Liechtenstein',
            'LT' => 'Lithuania',
            'LU' => 'Luxembourg',
            'MO' => 'Macau SAR China',
            'MK' => 'Macedonia',
            'MG' => 'Madagascar',
            'MW' => 'Malawi',
            'MY' => 'Malaysia',
            'MV' => 'Maldives',
            'ML' => 'Mali',
            'MT' => 'Malta',
            'MH' => 'Marshall Islands',
            'MQ' => 'Martinique',
            'MR' => 'Mauritania',
            'MU' => 'Mauritius',
            'YT' => 'Mayotte',
            'FX' => 'Metropolitan France',
            'MX' => 'Mexico',
            'FM' => 'Micronesia',
            'MI' => 'Midway Islands',
            'MD' => 'Moldova',
            'MC' => 'Monaco',
            'MN' => 'Mongolia',
            'ME' => 'Montenegro',
            'MS' => 'Montserrat',
            'MA' => 'Morocco',
            'MZ' => 'Mozambique',
            'MM' => 'Myanmar [Burma]',
            'NA' => 'Namibia',
            'NR' => 'Nauru',
            'NP' => 'Nepal',
            'NL' => 'Netherlands',
            'AN' => 'Netherlands Antilles',
            'NT' => 'Neutral Zone',
            'NC' => 'New Caledonia',
            'NZ' => 'New Zealand',
            'NI' => 'Nicaragua',
            'NE' => 'Niger',
            'NG' => 'Nigeria',
            'NU' => 'Niue',
            'NF' => 'Norfolk Island',
            'KP' => 'North Korea',
            'VD' => 'North Vietnam',
            'MP' => 'Northern Mariana Islands',
            'NO' => 'Norway',
            'OM' => 'Oman',
            'PC' => 'Pacific Islands Trust Territory',
            'PK' => 'Pakistan',
            'PW' => 'Palau',
            'PS' => 'Palestinian Territories',
            'PA' => 'Panama',
            'PZ' => 'Panama Canal Zone',
            'PG' => 'Papua New Guinea',
            'PY' => 'Paraguay',
            'YD' => 'People\'s Democratic Republic of Yemen',
            'PE' => 'Peru',
            'PH' => 'Philippines',
            'PN' => 'Pitcairn Islands',
            'PL' => 'Poland',
            'PT' => 'Portugal',
            'PR' => 'Puerto Rico',
            'QA' => 'Qatar',
            'RO' => 'Romania',
            'RU' => 'Russia',
            'RW' => 'Rwanda',
            'RE' => 'Réunion',
            'BL' => 'Saint Barthélemy',
            'SH' => 'Saint Helena',
            'KN' => 'Saint Kitts and Nevis',
            'LC' => 'Saint Lucia',
            'MF' => 'Saint Martin',
            'PM' => 'Saint Pierre and Miquelon',
            'VC' => 'Saint Vincent and the Grenadines',
            'WS' => 'Samoa',
            'SM' => 'San Marino',
            'SA' => 'Saudi Arabia',
            'SN' => 'Senegal',
            'RS' => 'Serbia',
            'CS' => 'Serbia and Montenegro',
            'SC' => 'Seychelles',
            'SL' => 'Sierra Leone',
            'SG' => 'Singapore',
            'SK' => 'Slovakia',
            'SI' => 'Slovenia',
            'SB' => 'Solomon Islands',
            'SO' => 'Somalia',
            'ZA' => 'South Africa',
            'GS' => 'South Georgia and the South Sandwich Islands',
            'KR' => 'South Korea',
            'ES' => 'Spain',
            'LK' => 'Sri Lanka',
            'SD' => 'Sudan',
            'SR' => 'Suriname',
            'SJ' => 'Svalbard and Jan Mayen',
            'SZ' => 'Swaziland',
            'SE' => 'Sweden',
            'CH' => 'Switzerland',
            'SY' => 'Syria',
            'ST' => 'São Tomé and Príncipe',
            'TW' => 'Taiwan',
            'TJ' => 'Tajikistan',
            'TZ' => 'Tanzania',
            'TH' => 'Thailand',
            'TL' => 'Timor-Leste',
            'TG' => 'Togo',
            'TK' => 'Tokelau',
            'TO' => 'Tonga',
            'TT' => 'Trinidad and Tobago',
            'TN' => 'Tunisia',
            'TR' => 'Turkey',
            'TM' => 'Turkmenistan',
            'TC' => 'Turks and Caicos Islands',
            'TV' => 'Tuvalu',
            'UM' => 'U.S. Minor Outlying Islands',
            'PU' => 'U.S. Miscellaneous Pacific Islands',
            'VI' => 'U.S. Virgin Islands',
            'UG' => 'Uganda',
            'UA' => 'Ukraine',
            'SU' => 'Union of Soviet Socialist Republics',
            'AE' => 'United Arab Emirates',
            'GB' => 'United Kingdom',
            'US' => 'United States',
            'UY' => 'Uruguay',
            'UZ' => 'Uzbekistan',
            'VU' => 'Vanuatu',
            'VA' => 'Vatican City',
            'VE' => 'Venezuela',
            'VN' => 'Vietnam',
            'WK' => 'Wake Island',
            'WF' => 'Wallis and Futuna',
            'EH' => 'Western Sahara',
            'YE' => 'Yemen',
            'ZM' => 'Zambia',
            'ZW' => 'Zimbabwe',
            'AX' => 'Åland Islands',
        ];
    }

    public static function getCountryCodes(): array
    {
        return array_keys(self::getCountries());
    }

    public static function getCountryCodesCommaSeparated(): string
    {
        return implode(',', self::getCountryCodes());
    }

    public static function getUsStates(): array
    {
        return [
            'AL' => 'Alabama',
            'AK' => 'Alaska',
            'AZ' => 'Arizona',
            'AR' => 'Arkansas',
            'CA' => 'California',
            'CO' => 'Colorado',
            'CT' => 'Connecticut',
            'DE' => 'Delaware',
            'FL' => 'Florida',
            'GA' => 'Georgia',
            'HI' => 'Hawaii',
            'ID' => 'Idaho',
            'IL' => 'Illinois',
            'IN' => 'Indiana',
            'IA' => 'Iowa',
            'KS' => 'Kansas',
            'KY' => 'Kentucky',
            'LA' => 'Louisiana',
            'ME' => 'Maine',
            'MD' => 'Maryland',
            'MA' => 'Massachusetts',
            'MI' => 'Michigan',
            'MN' => 'Minnesota',
            'MS' => 'Mississippi',
            'MO' => 'Missouri',
            'MT' => 'Montana',
            'NE' => 'Nebraska',
            'NV' => 'Nevada',
            'NH' => 'New Hampshire',
            'NJ' => 'New Jersey',
            'NM' => 'New Mexico',
            'NY' => 'New York',
            'NC' => 'North Carolina',
            'ND' => 'North Dakota',
            'OH' => 'Ohio',
            'OK' => 'Oklahoma',
            'OR' => 'Oregon',
            'PA' => 'Pennsylvania',
            'PR' => 'Puerto Rico',
            'RI' => 'Rhode Island',
            'SC' => 'South Carolina',
            'SD' => 'South Dakota',
            'TN' => 'Tennessee',
            'TX' => 'Texas',
            'VI' => 'U.S. Virgin Islands',
            'UT' => 'Utah',
            'VT' => 'Vermont',
            'VA' => 'Virginia',
            'WA' => 'Washington',
            'DC' => 'Washington DC',
            'WV' => 'West Virginia',
            'WI' => 'Wisconsin',
            'WY' => 'Wyoming'
        ];
    }

    public static function getUsStateCodes(): array
    {
        return array_keys(self::getUsStates());
    }

    public static function getUsStateCodesCommaSeparated(): string
    {
        return implode(',', self::getUsStateCodes());
    }

    public static function getAxiomePaymentsCountries(): array
    {
        return [
            ['code' => 'AD', 'name' => 'Andorra', 'phone' => '+376', 'flag' => '🇦🇩'],
            ['code' => 'AE', 'name' => 'United Arab Emirates', 'phone' => '+971', 'flag' => '🇦🇪'],
            ['code' => 'AG', 'name' => 'Antigua and Barbuda', 'phone' => '+1268', 'flag' => '🇦🇬'],
            ['code' => 'AI', 'name' => 'Anguilla', 'phone' => '+1264', 'flag' => '🇦🇮'],
            ['code' => 'AL', 'name' => 'Albania', 'phone' => '+355', 'flag' => '🇦🇱'],
            ['code' => 'AM', 'name' => 'Armenia', 'phone' => '+374', 'flag' => '🇦🇲'],
            ['code' => 'AO', 'name' => 'Angola', 'phone' => '+244', 'flag' => '🇦🇴'],
            ['code' => 'AR', 'name' => 'Argentina', 'phone' => '+54', 'flag' => '🇦🇷'],
            ['code' => 'AS', 'name' => 'American Samoa', 'phone' => '+1684', 'flag' => '🇦🇸'],
            ['code' => 'AT', 'name' => 'Austria', 'phone' => '+43', 'flag' => '🇦🇹'],
            ['code' => 'AU', 'name' => 'Australia', 'phone' => '+61', 'flag' => '🇦🇺'],
            ['code' => 'AW', 'name' => 'Aruba', 'phone' => '+297', 'flag' => '🇦🇼'],
            ['code' => 'AX', 'name' => 'Åland Islands', 'phone' => '+358', 'flag' => '🇦🇽'],
            ['code' => 'AZ', 'name' => 'Azerbaijan', 'phone' => '+994', 'flag' => '🇦🇿'],
            ['code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'phone' => '+387', 'flag' => '🇧🇦'],
            ['code' => 'BB', 'name' => 'Barbados', 'phone' => '+1246', 'flag' => '🇧🇧'],
            ['code' => 'BD', 'name' => 'Bangladesh', 'phone' => '+880', 'flag' => '🇧🇩'],
            ['code' => 'BE', 'name' => 'Belgium', 'phone' => '+32', 'flag' => '🇧🇪'],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'phone' => '+226', 'flag' => '🇧🇫'],
            ['code' => 'BG', 'name' => 'Bulgaria', 'phone' => '+359', 'flag' => '🇧🇬'],
            ['code' => 'BH', 'name' => 'Bahrain', 'phone' => '+973', 'flag' => '🇧🇭'],
            ['code' => 'BI', 'name' => 'Burundi', 'phone' => '+257', 'flag' => '🇧🇮'],
            ['code' => 'BJ', 'name' => 'Benin', 'phone' => '+229', 'flag' => '🇧🇯'],
            ['code' => 'BL', 'name' => 'Saint Barthélemy', 'phone' => '+590', 'flag' => '🇧🇱'],
            ['code' => 'BM', 'name' => 'Bermuda', 'phone' => '+1441', 'flag' => '🇧🇲'],
            ['code' => 'BN', 'name' => 'Brunei Darussalam', 'phone' => '+673', 'flag' => '🇧🇳'],
            ['code' => 'BO', 'name' => 'Bolivia', 'phone' => '+591', 'flag' => '🇧🇴'],
            ['code' => 'BQ', 'name' => 'Bonaire, Sint Eustatius and Saba', 'phone' => '+599', 'flag' => '🇧🇶'],
            ['code' => 'BR', 'name' => 'Brazil', 'phone' => '+55', 'flag' => '🇧🇷'],
            ['code' => 'BS', 'name' => 'Bahamas', 'phone' => '+1242', 'flag' => '🇧🇸'],
            ['code' => 'BT', 'name' => 'Bhutan', 'phone' => '+975', 'flag' => '🇧🇹'],
            //['code' => 'BW', 'name' => 'Botswana', 'phone' => '+267', 'flag' => '🇧🇼'],
            ['code' => 'BZ', 'name' => 'Belize', 'phone' => '+501', 'flag' => '🇧🇿'],
            ['code' => 'CA', 'name' => 'Canada', 'phone' => '+1', 'flag' => '🇨🇦'],
            ['code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'phone' => '+61', 'flag' => '🇨🇨'],
            ['code' => 'CF', 'name' => 'Central African Republic', 'phone' => '+236', 'flag' => '🇨🇫'],
            ['code' => 'CG', 'name' => 'Republic of the Congo', 'phone' => '+242', 'flag' => '🇨🇬'],
            ['code' => 'CH', 'name' => 'Switzerland', 'phone' => '+41', 'flag' => '🇨🇭'],
            ['code' => 'CI', 'name' => 'Cote D\'Ivoire', 'phone' => '+225', 'flag' => '🇨🇮'],
            ['code' => 'CK', 'name' => 'Cook Islands', 'phone' => '+682', 'flag' => '🇨🇰'],
            ['code' => 'CL', 'name' => 'Chile', 'phone' => '+56', 'flag' => '🇨🇱'],
            ['code' => 'CM', 'name' => 'Cameroon', 'phone' => '+237', 'flag' => '🇨🇲'],
            ['code' => 'CN', 'name' => 'China', 'phone' => '+86', 'flag' => '🇨🇳'],
            ['code' => 'CO', 'name' => 'Colombia', 'phone' => '+57', 'flag' => '🇨🇴'],
            ['code' => 'CR', 'name' => 'Costa Rica', 'phone' => '+506', 'flag' => '🇨🇷'],
            ['code' => 'CV', 'name' => 'Cape Verde (Cabo Verde)', 'phone' => '+238', 'flag' => '🇨🇻'],
            ['code' => 'CW', 'name' => 'Curaçao', 'phone' => '+599', 'flag' => '🇨🇼'],
            ['code' => 'CX', 'name' => 'Christmas Island', 'phone' => '+61', 'flag' => '🇨🇽'],
            ['code' => 'CY', 'name' => 'Cyprus', 'phone' => '+357', 'flag' => '🇨🇾'],
            ['code' => 'CZ', 'name' => 'Czech Republic', 'phone' => '+420', 'flag' => '🇨🇿'],
            ['code' => 'DE', 'name' => 'Germany', 'phone' => '+49', 'flag' => '🇩🇪'],
            ['code' => 'DJ', 'name' => 'Djibouti', 'phone' => '+253', 'flag' => '🇩🇯'],
            ['code' => 'DK', 'name' => 'Denmark', 'phone' => '+45', 'flag' => '🇩🇰'],
            ['code' => 'DM', 'name' => 'Dominica', 'phone' => '+1767', 'flag' => '🇩🇲'],
            ['code' => 'DO', 'name' => 'Dominican Republic', 'phone' => '+1809', 'flag' => '🇩🇴'],
            ['code' => 'DZ', 'name' => 'Algeria', 'phone' => '+213', 'flag' => '🇩🇿'],
            ['code' => 'EC', 'name' => 'Ecuador', 'phone' => '+593', 'flag' => '🇪🇨'],
            ['code' => 'EE', 'name' => 'Estonia', 'phone' => '+372', 'flag' => '🇪🇪'],
            ['code' => 'EH', 'name' => 'Western Sahara', 'phone' => '+212', 'flag' => '🇪🇭'],
            ['code' => 'ER', 'name' => 'Eritrea', 'phone' => '+291', 'flag' => '🇪🇷'],
            ['code' => 'ES', 'name' => 'Spain', 'phone' => '+34', 'flag' => '🇪🇸'],
            ['code' => 'ET', 'name' => 'Ethiopia', 'phone' => '+251', 'flag' => '🇪🇹'],
            ['code' => 'FI', 'name' => 'Finland', 'phone' => '+358', 'flag' => '🇫🇮'],
            ['code' => 'FJ', 'name' => 'Fiji', 'phone' => '+679', 'flag' => '🇫🇯'],
            ['code' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'phone' => '+500', 'flag' => '🇫🇰'],
            ['code' => 'FM', 'name' => 'Micronesia', 'phone' => '+691', 'flag' => '🇫🇲'],
            ['code' => 'FO', 'name' => 'Faroe Islands', 'phone' => '+298', 'flag' => '🇫🇴'],
            ['code' => 'FR', 'name' => 'France', 'phone' => '+33', 'flag' => '🇫🇷'],
            ['code' => 'GA', 'name' => 'Gabon', 'phone' => '+241', 'flag' => '🇬🇦'],
            ['code' => 'GB', 'name' => 'United Kingdom', 'phone' => '+44', 'flag' => '🇬🇧'],
            ['code' => 'GD', 'name' => 'Grenada', 'phone' => '+1473', 'flag' => '🇬🇩'],
            ['code' => 'GE', 'name' => 'Georgia', 'phone' => '+995', 'flag' => '🇬🇪'],
            ['code' => 'GF', 'name' => 'French Guiana', 'phone' => '+594', 'flag' => '🇬🇫'],
            ['code' => 'GG', 'name' => 'Guernsey', 'phone' => '+44', 'flag' => '🇬🇬'],
            ['code' => 'GH', 'name' => 'Ghana', 'phone' => '+233', 'flag' => '🇬🇭'],
            ['code' => 'GL', 'name' => 'Greenland', 'phone' => '+299', 'flag' => '🇬🇱'],
            ['code' => 'GM', 'name' => 'Gambia', 'phone' => '+220', 'flag' => '🇬🇲'],
            ['code' => 'GN', 'name' => 'Guinea', 'phone' => '+224', 'flag' => '🇬🇳'],
            ['code' => 'GP', 'name' => 'Guadeloupe', 'phone' => '+590', 'flag' => '🇬🇵'],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'phone' => '+240', 'flag' => '🇬🇶'],
            ['code' => 'GR', 'name' => 'Greece', 'phone' => '+30', 'flag' => '🇬🇷'],
            ['code' => 'GT', 'name' => 'Guatemala', 'phone' => '+502', 'flag' => '🇬🇹'],
            ['code' => 'GU', 'name' => 'Guam', 'phone' => '+1671', 'flag' => '🇬🇺'],
            ['code' => 'GW', 'name' => 'Guinea-Bissau', 'phone' => '+245', 'flag' => '🇬🇼'],
            ['code' => 'GY', 'name' => 'Guyana', 'phone' => '+592', 'flag' => '🇬🇾'],
            ['code' => 'HK', 'name' => 'Hong Kong', 'phone' => '+852', 'flag' => '🇭🇰'],
            ['code' => 'HN', 'name' => 'Honduras', 'phone' => '+504', 'flag' => '🇭🇳'],
            ['code' => 'HR', 'name' => 'Croatia', 'phone' => '+385', 'flag' => '🇭🇷'],
            ['code' => 'HT', 'name' => 'Haiti', 'phone' => '+509', 'flag' => '🇭🇹'],
            ['code' => 'HU', 'name' => 'Hungary', 'phone' => '+36', 'flag' => '🇭🇺'],
            ['code' => 'ID', 'name' => 'Indonesia', 'phone' => '+62', 'flag' => '🇮🇩'],
            ['code' => 'IE', 'name' => 'Ireland', 'phone' => '+353', 'flag' => '🇮🇪'],
            ['code' => 'IL', 'name' => 'Israel', 'phone' => '+972', 'flag' => '🇮🇱'],
            ['code' => 'IM', 'name' => 'Isle of Man', 'phone' => '+44', 'flag' => '🇮🇲'],
            ['code' => 'IN', 'name' => 'India', 'phone' => '+91', 'flag' => '🇮🇳'],
            ['code' => 'IO', 'name' => 'British Indian Ocean Territory', 'phone' => '+246', 'flag' => '🇮🇴'],
            ['code' => 'IS', 'name' => 'Iceland', 'phone' => '+354', 'flag' => '🇮🇸'],
            ['code' => 'IT', 'name' => 'Italy', 'phone' => '+39', 'flag' => '🇮🇹'],
            ['code' => 'JE', 'name' => 'Jersey', 'phone' => '+44', 'flag' => '🇯🇪'],
            ['code' => 'JM', 'name' => 'Jamaica', 'phone' => '+1876', 'flag' => '🇯🇲'],
            ['code' => 'JO', 'name' => 'Jordan', 'phone' => '+962', 'flag' => '🇯🇴'],
            ['code' => 'JP', 'name' => 'Japan', 'phone' => '+81', 'flag' => '🇯🇵'],
            ['code' => 'KE', 'name' => 'Kenya', 'phone' => '+254', 'flag' => '🇰🇪'],
            ['code' => 'KG', 'name' => 'Kyrgyzstan', 'phone' => '+996', 'flag' => '🇰🇬'],
            ['code' => 'KH', 'name' => 'Cambodia', 'phone' => '+855', 'flag' => '🇰🇭'],
            ['code' => 'KI', 'name' => 'Kiribati', 'phone' => '+686', 'flag' => '🇰🇮'],
            ['code' => 'KM', 'name' => 'Comoros', 'phone' => '+269', 'flag' => '🇰🇲'],
            ['code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'phone' => '+1869', 'flag' => '🇰🇳'],
            ['code' => 'KR', 'name' => 'South Korea', 'phone' => '+82', 'flag' => '🇰🇷'],
            ['code' => 'KW', 'name' => 'Kuwait', 'phone' => '+965', 'flag' => '🇰🇼'],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'phone' => '+7', 'flag' => '🇰🇿'],
            ['code' => 'LA', 'name' => 'Laos', 'phone' => '+856', 'flag' => '🇱🇦'],
            ['code' => 'LB', 'name' => 'Lebanon', 'phone' => '+961', 'flag' => '🇱🇧'],
            ['code' => 'LC', 'name' => 'Saint Lucia', 'phone' => '+1758', 'flag' => '🇱🇨'],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'phone' => '+423', 'flag' => '🇱🇮'],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'phone' => '+94', 'flag' => '🇱🇰'],
            ['code' => 'LR', 'name' => 'Liberia', 'phone' => '+231', 'flag' => '🇱🇷'],
            ['code' => 'LS', 'name' => 'Lesotho', 'phone' => '+266', 'flag' => '🇱🇸'],
            ['code' => 'LT', 'name' => 'Lithuania', 'phone' => '+370', 'flag' => '🇱🇹'],
            ['code' => 'LU', 'name' => 'Luxembourg', 'phone' => '+352', 'flag' => '🇱🇺'],
            ['code' => 'LV', 'name' => 'Latvia', 'phone' => '+371', 'flag' => '🇱🇻'],
            ['code' => 'LY', 'name' => 'Libya', 'phone' => '+218', 'flag' => '🇱🇾'],
            ['code' => 'MA', 'name' => 'Morocco', 'phone' => '+212', 'flag' => '🇲🇦'],
            ['code' => 'MC', 'name' => 'Monaco', 'phone' => '+377', 'flag' => '🇲🇨'],
            ['code' => 'MD', 'name' => 'Moldova', 'phone' => '+373', 'flag' => '🇲🇩'],
            ['code' => 'ME', 'name' => 'Montenegro', 'phone' => '+382', 'flag' => '🇲🇪'],
            ['code' => 'MF', 'name' => 'Saint Martin (French part)', 'phone' => '+590', 'flag' => '🇲🇫'],
            ['code' => 'MG', 'name' => 'Madagascar', 'phone' => '+261', 'flag' => '🇲🇬'],
            ['code' => 'MH', 'name' => 'Marshall Islands', 'phone' => '+692', 'flag' => '🇲🇭'],
            ['code' => 'MK', 'name' => 'Macedonia', 'phone' => '+389', 'flag' => '🇲🇰'],
            ['code' => 'ML', 'name' => 'Mali', 'phone' => '+223', 'flag' => '🇲🇱'],
            ['code' => 'MM', 'name' => 'Myanmar (Burma)', 'phone' => '+95', 'flag' => '🇲🇲'],
            ['code' => 'MN', 'name' => 'Mongolia', 'phone' => '+976', 'flag' => '🇲🇳'],
            ['code' => 'MO', 'name' => 'Macau', 'phone' => '+853', 'flag' => '🇲🇴'],
            ['code' => 'MP', 'name' => 'Northern Mariana Islands', 'phone' => '+1670', 'flag' => '🇲🇵'],
            ['code' => 'MQ', 'name' => 'Martinique', 'phone' => '+596', 'flag' => '🇲🇶'],
            ['code' => 'MR', 'name' => 'Mauritania', 'phone' => '+222', 'flag' => '🇲🇷'],
            ['code' => 'MS', 'name' => 'Montserrat', 'phone' => '+1664', 'flag' => '🇲🇸'],
            ['code' => 'MT', 'name' => 'Malta', 'phone' => '+356', 'flag' => '🇲🇹'],
            ['code' => 'MU', 'name' => 'Mauritius', 'phone' => '+230', 'flag' => '🇲🇺'],
            ['code' => 'MV', 'name' => 'Maldives', 'phone' => '+960', 'flag' => '🇲🇻'],
            ['code' => 'MW', 'name' => 'Malawi', 'phone' => '+265', 'flag' => '🇲🇼'],
            ['code' => 'MX', 'name' => 'Mexico', 'phone' => '+52', 'flag' => '🇲🇽'],
            ['code' => 'MY', 'name' => 'Malaysia', 'phone' => '+60', 'flag' => '🇲🇾'],
            ['code' => 'MZ', 'name' => 'Mozambique', 'phone' => '+258', 'flag' => '🇲🇿'],
            ['code' => 'NA', 'name' => 'Namibia', 'phone' => '+264', 'flag' => '🇳🇦'],
            ['code' => 'NC', 'name' => 'New Caledonia', 'phone' => '+687', 'flag' => '🇳🇨'],
            ['code' => 'NE', 'name' => 'Niger', 'phone' => '+227', 'flag' => '🇳🇪'],
            ['code' => 'NF', 'name' => 'Norfolk Island', 'phone' => '+672', 'flag' => '🇳🇫'],
            ['code' => 'NG', 'name' => 'Nigeria', 'phone' => '+234', 'flag' => '🇳🇬'],
            ['code' => 'NI', 'name' => 'Nicaragua', 'phone' => '+505', 'flag' => '🇳🇮'],
            ['code' => 'NL', 'name' => 'Netherlands', 'phone' => '+31', 'flag' => '🇳🇱'],
            ['code' => 'NO', 'name' => 'Norway', 'phone' => '+47', 'flag' => '🇳🇴'],
            ['code' => 'NR', 'name' => 'Nauru', 'phone' => '+674', 'flag' => '🇳🇷'],
            ['code' => 'NU', 'name' => 'Niue', 'phone' => '+683', 'flag' => '🇳🇺'],
            ['code' => 'NZ', 'name' => 'New Zealand', 'phone' => '+64', 'flag' => '🇳🇿'],
            ['code' => 'OM', 'name' => 'Oman', 'phone' => '+968', 'flag' => '🇴🇲'],
            ['code' => 'PA', 'name' => 'Panama', 'phone' => '+507', 'flag' => '🇵🇦'],
            ['code' => 'PE', 'name' => 'Peru', 'phone' => '+51', 'flag' => '🇵🇪'],
            ['code' => 'PF', 'name' => 'French Polynesia', 'phone' => '+689', 'flag' => '🇵🇫'],
            ['code' => 'PG', 'name' => 'Papua New Guinea', 'phone' => '+675', 'flag' => '🇵🇬'],
            ['code' => 'PH', 'name' => 'Philippines', 'phone' => '+63', 'flag' => '🇵🇭'],
            ['code' => 'PK', 'name' => 'Pakistan', 'phone' => '+92', 'flag' => '🇵🇰'],
            ['code' => 'PL', 'name' => 'Poland', 'phone' => '+48', 'flag' => '🇵🇱'],
            ['code' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'phone' => '+508', 'flag' => '🇵🇲'],
            ['code' => 'PN', 'name' => 'Pitcairn', 'phone' => '+64', 'flag' => '🇵🇳'],
            ['code' => 'PR', 'name' => 'Puerto Rico', 'phone' => '+1', 'flag' => '🇵🇷'],
            ['code' => 'PS', 'name' => 'Palestine', 'phone' => '+970', 'flag' => '🇵🇸'],
            ['code' => 'PT', 'name' => 'Portugal', 'phone' => '+351', 'flag' => '🇵🇹'],
            ['code' => 'PW', 'name' => 'Palau', 'phone' => '+680', 'flag' => '🇵🇼'],
            ['code' => 'PY', 'name' => 'Paraguay', 'phone' => '+595', 'flag' => '🇵🇾'],
            ['code' => 'QA', 'name' => 'Qatar', 'phone' => '+974', 'flag' => '🇶🇦'],
            ['code' => 'RE', 'name' => 'Réunion', 'phone' => '+262', 'flag' => '🇷🇪'],
            ['code' => 'RO', 'name' => 'Romania', 'phone' => '+40', 'flag' => '🇷🇴'],
            ['code' => 'RS', 'name' => 'Serbia', 'phone' => '+381', 'flag' => '🇷🇸'],
            ['code' => 'RW', 'name' => 'Rwanda', 'phone' => '+250', 'flag' => '🇷🇼'],
            ['code' => 'SA', 'name' => 'Saudi Arabia', 'phone' => '+966', 'flag' => '🇸🇦'],
            ['code' => 'SB', 'name' => 'Solomon Islands', 'phone' => '+677', 'flag' => '🇸🇧'],
            ['code' => 'SC', 'name' => 'Seychelles', 'phone' => '+248', 'flag' => '🇸🇨'],
            ['code' => 'SE', 'name' => 'Sweden', 'phone' => '+46', 'flag' => '🇸🇪'],
            ['code' => 'SG', 'name' => 'Singapore', 'phone' => '+65', 'flag' => '🇸🇬'],
            ['code' => 'SH', 'name' => 'Saint Helena, Ascension and Tristan da Cunha', 'phone' => '+290', 'flag' => '🇸🇭'],
            ['code' => 'SI', 'name' => 'Slovenia', 'phone' => '+386', 'flag' => '🇸🇮'],
            ['code' => 'SJ', 'name' => 'Svalbard and Jan Mayen', 'phone' => '+47', 'flag' => '🇸🇯'],
            ['code' => 'SK', 'name' => 'Slovakia', 'phone' => '+421', 'flag' => '🇸🇰'],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'phone' => '+232', 'flag' => '🇸🇱'],
            ['code' => 'SM', 'name' => 'San Marino', 'phone' => '+378', 'flag' => '🇸🇲'],
            ['code' => 'SN', 'name' => 'Senegal', 'phone' => '+221', 'flag' => '🇸🇳'],
            ['code' => 'SO', 'name' => 'Somalia', 'phone' => '+252', 'flag' => '🇸🇴'],
            ['code' => 'SR', 'name' => 'Suriname', 'phone' => '+597', 'flag' => '🇸🇷'],
            ['code' => 'ST', 'name' => 'São Tomé and Príncipe', 'phone' => '+239', 'flag' => '🇸🇹'],
            ['code' => 'SV', 'name' => 'El Salvador', 'phone' => '+503', 'flag' => '🇸🇻'],
            ['code' => 'SX', 'name' => 'Sint Maarten', 'phone' => '+1721', 'flag' => '🇸🇽'],
            ['code' => 'SZ', 'name' => 'Eswatini (Swaziland)', 'phone' => '+268', 'flag' => '🇸🇿'],
            ['code' => 'TC', 'name' => 'Turks and Caicos Islands', 'phone' => '+1649', 'flag' => '🇹🇨'],
            ['code' => 'TD', 'name' => 'Chad', 'phone' => '+235', 'flag' => '🇹🇩'],
            ['code' => 'TG', 'name' => 'Togo', 'phone' => '+228', 'flag' => '🇹🇬'],
            ['code' => 'TH', 'name' => 'Thailand', 'phone' => '+66', 'flag' => '🇹🇭'],
            ['code' => 'TJ', 'name' => 'Tajikistan', 'phone' => '+992', 'flag' => '🇹🇯'],
            ['code' => 'TK', 'name' => 'Tokelau', 'phone' => '+690', 'flag' => '🇹🇰'],
            ['code' => 'TL', 'name' => 'Timor-Leste', 'phone' => '+670', 'flag' => '🇹🇱'],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'phone' => '+993', 'flag' => '🇹🇲'],
            ['code' => 'TO', 'name' => 'Tonga', 'phone' => '+676', 'flag' => '🇹🇴'],
            ['code' => 'TR', 'name' => 'Turkey', 'phone' => '+90', 'flag' => '🇹🇷'],
            ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'phone' => '+1868', 'flag' => '🇹🇹'],
            ['code' => 'TV', 'name' => 'Tuvalu', 'phone' => '+688', 'flag' => '🇹🇻'],
            ['code' => 'TW', 'name' => 'Taiwan', 'phone' => '+886', 'flag' => '🇹🇼'],
            ['code' => 'TZ', 'name' => 'Tanzania', 'phone' => '+255', 'flag' => '🇹🇿'],
            ['code' => 'UA', 'name' => 'Ukraine', 'phone' => '+380', 'flag' => '🇺🇦'],
            ['code' => 'UG', 'name' => 'Uganda', 'phone' => '+256', 'flag' => '🇺🇬'],
            ['code' => 'US', 'name' => 'United States', 'phone' => '+1', 'flag' => '🇺🇸'],
            ['code' => 'UY', 'name' => 'Uruguay', 'phone' => '+598', 'flag' => '🇺🇾'],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'phone' => '+998', 'flag' => '🇺🇿'],
            ['code' => 'VA', 'name' => 'Vatican City (Holy See)', 'phone' => '+379', 'flag' => '🇻🇦'],
            ['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'phone' => '+1784', 'flag' => '🇻🇨'],
            ['code' => 'VG', 'name' => 'British Virgin Islands', 'phone' => '+1284', 'flag' => '🇻🇬'],
            ['code' => 'VI', 'name' => 'United States Virgin Islands', 'phone' => '+1340', 'flag' => '🇻🇮'],
            ['code' => 'VN', 'name' => 'Vietnam', 'phone' => '+84', 'flag' => '🇻🇳'],
            ['code' => 'VU', 'name' => 'Vanuatu', 'phone' => '+678', 'flag' => '🇻🇺'],
            ['code' => 'WF', 'name' => 'Wallis and Futuna', 'phone' => '+681', 'flag' => '🇼🇫'],
            ['code' => 'WS', 'name' => 'Samoa', 'phone' => '+685', 'flag' => '🇼🇸'],
            ['code' => 'XK', 'name' => 'Kosovo', 'phone' => '+383', 'flag' => '🇽🇰'],
            ['code' => 'YE', 'name' => 'Yemen', 'phone' => '+967', 'flag' => '🇾🇪'],
            ['code' => 'YT', 'name' => 'Mayotte', 'phone' => '+262', 'flag' => '🇾🇹'],
            ['code' => 'ZA', 'name' => 'South Africa', 'phone' => '+27', 'flag' => '🇿🇦'],
            ['code' => 'ZM', 'name' => 'Zambia', 'phone' => '+260', 'flag' => '🇿🇲'],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'phone' => '+263', 'flag' => '🇿🇼']
        ];
    }

    public static function getAxiomePaymentsCountryCodes(): array
    {
        return $GLOBALS['TV_COUNTRY_CODES']
            ?? $GLOBALS['TV_COUNTRY_CODES'] = array_map(function (array $country) {
            return $country['code'];
        }, self::getAxiomePaymentsCountries());
    }

    public static function isCountryAxiomePaymentsSupported(string $countryCode): bool
    {
        return in_array($countryCode, self::getAxiomePaymentsCountryCodes());
    }
}